### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ryandeba** [ryandeba/set#1]
- [ ] join recently unfinished games
- [ ] leave/stop game
- [ ] share join link
- [ ] messages from players (bubble under/near player chip; most recent only; max 50 characters; auto-clear after 10 seconds; attention on new
- [ ] do not allow clearing modals
- [ ] game over options (new game, message emoji reactions, fun awards/labels/animations)
- [ ] lose points for incorrect guesses (look up the actual rules!)
- [ ] lock game when entering set (5 seconds to enter; player cannot lock again for 5 seconds after if incorrect or times out)
- [ ] better players ui (colors, icons, etc)
- [ ] auto-delete finished games after some amount of time (or just delete nedb.db?)
- [ ] nodejs for production (run as service; auto start; better error handling; restart after crash; etc)
- [ ] location pushState and/or vue routes
- [ ] remember username (but give some way to delete/change it? probs not during a game...or refactor players :thinking:)
- [ ] ui settings (light/dark, card theme)
- [ ] better transitions/states (loading, between states, card movements, etc)

**Comment by ryandeba** [comment]
Consider these for game settings:

Modes
- standard (done)
- shuffle after each set
  - random, easy, medium, or hard. harder difficulties prefer fewer possible sets.

Allow enabling hints (the to-do for training mode)

Deduct points for incorrect guesses

**Comment by ryandeba** [comment]
Maybe allow deselecting only if there are 2 cards selected. Going 1 to 0 seems weird...and 3 will submit the set.
